### ISSUE TITLE
Script for spawning robot problem

### ISSUE THREAD

**Issue by andrecabaco** [miguelriemoliveira/PSA-P2-21-22#1]
Boa tarde professor @miguelriemoliveira , estou com um problema ao lançar o código para dar spawn no robot. Consigo lançar os dois primeiros comandos mas aparece-me o seguinte ao lançar o terceiro:

resource not found: turtlebot3_description
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/pabundz/catkin_ws/src
ROS path [2]=/home/pabundz/catkin_ws/src
ROS path [3]=/opt/ros/noetic/share
when processing file: /home/pabundz/catkin_ws/src/PSA-P2-21-22/psa_robot_description/urdf/properties.xacro
included from: /home/pabundz/catkin_ws/src/PSA-P2-21-22/psa_robot_description/urdf/psa_robot.urdf.xacro
RLException: Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/noetic/lib/xacro/xacro', '/home/pabundz/catkin_ws/src/PSA-P2-21-22/psa_robot_description/urdf/psa_robot.urdf.xacro', 'name:=psa_robot', 'color:=Red']] returned with code [2]. 

Param xml is <param name="robot_description" command="$(find xacro)/xacro '$(find psa_robot_description)/urdf/psa_robot.urdf.xacro' name:=$(arg name) color:=$(arg color)"/>
The traceback for the exception was written to the log file

Já incluí os exports para os turtlebot:
export TURTLEBOT3_MODEL=burger
export TURTLEBOT3_MODEL=waffle
export TURTLEBOT3_MODEL=waffle_pi

Também já instalei o que o professor mencionou no final do README.

Não consegui ir à reunião de dúvidas na 2ª feira, pelo que não consegui tirar a dúvida.

Penso que me esteja a faltar algo mas não sei o que é.

Obrigado

**Comment by miguelriemoliveira** [comment]
Olá @andrecabaco ,

falta-lhe instalar o turtlebot3. 

https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/
https://emanual.robotis.com/docs/en/platform/turtlebot3/simulation/

**Comment by andrecabaco** [comment]
Era isso, obrigado professor @miguelriemoliveira. Vou fechar o issue, uma vez que o problema foi resolvido.
