### ISSUE TITLE
ERROR "Resource not found" when running "roslaunch gazebo.launch" command (SOLVED)

### ISSUE THREAD

**Issue by vhfmaia** [miguelriemoliveira/PSA-P2-21-22#2]
![imagem](https://user-images.githubusercontent.com/101104948/170869992-eea8370e-1a85-42b2-a420-e62313a42a70.png)

SOLUÇÃO
o sistema não consegue encontrar o ros package chamado psa_fnr.

Para confirmar que é mesmo esse o problema pode correr o comando

roscd psa_fnr

Que deve falhar com um erro.

Este é um dos pacotes que está no repositório.

Há várias razões possíveis para não estar a ser encontrado:

Não estar colocado dentro do catkin_ws/src

O seu terminal não estar devidamente configurado para correr ros, em particular  no seu ficheiro

~/.bashrc

deve ter estas linhas

export TURTLEBOT3_MODEL=waffle_pi
source /opt/ros/noetic/setup.bash
source ~/catkin_ws/devel/setup.bash
export ROS_PACKAGE_PATH=~/catkin_ws_rviz/src:${ROS_PACKAGE_PATH}

Pode ser necessário adaptar alguns caminhos.

**Comment by miguelriemoliveira** [comment]
Funciona?

**Comment by vhfmaia** [comment]
por acaso não, o erro continua o mesmo
(1) mudei a localização para catkin_ws/src - antes estava só no catkin
(2) corri o comando `xdg-open ~/.bashrc` e inseri as 4 linhas, tambem mudei o source do catkin que no meu caso, está inserido na pasta carla-ros-bridge
continua o mesmo erro
```

roslaunch gazebo.launch
... logging to /home/victor/.ros/log/856bab4e-df56-11ec-b908-b3fe4723fc21/roslaunch-victor-HP-Pavilion-Gaming-Laptop-15-ec1xxx-6039.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Resource not found: The following package was not found in <arg name="world_name" value="$(find psa_fnr)/worlds/$(arg world_name)"/>: psa_fnr
ROS path [0]=/opt/ros/noetic/share/ros
ROS path [1]=/home/victor/catkin_ws_rviz/src
ROS path [2]=/opt/ros/noetic/share
The traceback for the exception was written to the log file

```

**Comment by miguelriemoliveira** [comment]
Olá @vhfmaia 

enquanto não conseguir fazer o 

roscd psa_fnr 

não vale a pena tentar o comando roslaunch.

Desligou o terminal e começou com um novo?

Qual é o output do comando

echo $ROS_PACKAGE_PATH

**Comment by vhfmaia** [comment]
Mas consigo correr o `roscd psa_fnr`:
```
victor@victor-HP-Pavilion-Gaming-Laptop-15-ec1xxx:~$ roscd psa_fnr
victor@victor-HP-Pavilion-Gaming-Laptop-15-ec1xxx:~/carla-ros-bridge/catkin_ws/src/PSA-P2-21-22/psa_fnr$ 
```

O output do comando `echo $ROS_PACKAGE_PATH` é:

```
victor@victor-HP-Pavilion-Gaming-Laptop-15-ec1xxx:~$ echo $ROS_PACKAGE_PATH
/home/victor/catkin_ws_rviz/src:/home/victor/carla-ros-bridge/catkin_ws/src:/opt/ros/noetic/share
victor@victor-HP-Pavilion-Gaming-Laptop-15-ec1xxx:~$
```

**Comment by vhfmaia** [comment]
Peço desculpas, reiniciei o ubuntu e tudo corre como deveria, obrigado @miguelriemoliveira!

**Comment by vhfmaia** [comment]
Outra solução para o problema é correr os seguintes comandos:
```
cd ~/catkin_ws/

catkin_make

source devel/setup.bash

echo $ROS_PACKAGE_PATH

```

**Comment by miguelriemoliveira** [comment]
Fixe!
